NewFunction: PortCheck / NewGlobalVar: PortLocation

diff --git a/00.Installation/function b/00.Installation/function
--- a/00.Installation/function
+++ b/00.Installation/function
@@ -4,7 +4,7 @@
 # Author: Aniverse
 #
 script_update=2020.03.05
-script_version=r10046
+script_version=r11047
 ################################################################################################ Usage Guide
 
 usage_guide() {
@@ -47,6 +47,7 @@ CW="${bold}${baihongse} ERROR ${jiacu}" ; ZY="${baihongse}${bold} ATTENTION ${ji
 
 LogBase=/log/inexistence
 LOCKLocation=$LogBase/lock
+PortLocation=$LogBase/port
 local_package=/etc/inexistence/00.Installation
 local_script=/usr/local/bin/abox
 web_root=/var/www
@@ -94,13 +95,13 @@ function status_failed() {
 	echo -e " ${red}${bold}FAILED${normal}" | tee -a $OutputLOG
 }
 function echo_warning() {
-    printf " ${yellow}${bold}WARNING: ${underline}%s${normal}\n" "$@" | tee -a $OutputLOG
+    printf " ${yellow}${bold}WARNING: %s${normal}\n" "$@" | tee -a $OutputLOG
 }
 function echo_error() {
-    printf " ${red}${bold}ERROR: ${underline}%s${normal}\n" "$@" | tee -a $OutputLOG       # ; exit 1
+    printf " ${red}${bold}ERROR: %s${normal}\n" "$@" | tee -a $OutputLOG       # ; exit 1
 }
 function echo_info() {
-    printf " ${cyan}${bold}Info: ${underline}%s${normal}\n" "$@" | tee -a $OutputLOG
+    printf " ${cyan}${bold}Info: %s${normal}\n" "$@" | tee -a $OutputLOG
 }
 
 # These codes are from teddysun bbr.sh
@@ -296,10 +297,18 @@ function apt_install_separate() {
 ################################################################################################
 
 
-PortGenerator1() { portGen1=$(shuf -i 10001-32001 -n1) ; } ; portGenerator2() { portGen2=$(shuf -i 10001-32001 -n1) ; }
-PortCheck()      { while ss -ln | grep ':'$portGen1'' | grep -q LISTEN ; do PortGenerator1 ; done ; }
+function PortCheck(){
+    ports=("$@")
+    for port in "${ports[@]}" ; do
+        if ss -ln | grep ':'$port'' | grep -q LISTEN ; then
+            echo_error "Port $port is already in use"
+            port_used=1
+        fi
+    done
+}
+PortGenerator1() { portGen1=$(shuf -i 10001-32001 -n1) ; }portGenerator2() { portGen2=$(shuf -i 10001-32001 -n1) ; }
+PortCheck1()     { while ss -ln | grep ':'$portGen1'' | grep -q LISTEN ; do PortGenerator1 ; done ; }
 PortCheck2()     { while ss -ln | grep ':'$portGen2'' | grep -q LISTEN ; do PortGenerator2 ; done ; }
-
 
 function check_remote_git_repo_branch() {
     [[ -z $(which git) ]] && { apt-get install -y git > /dev/null 2>&1 ; }
