function / apt_install_check && apt_install_separate

diff --git a/00.Installation/function b/00.Installation/function
--- a/00.Installation/function
+++ b/00.Installation/function
@@ -4,7 +4,7 @@
 # Author: Aniverse
 #
 script_update=2020.03.01
-script_version=r10038
+script_version=r10039
 ################################################################################################ Usage Guide
 
 usage_guide() {
@@ -154,24 +154,40 @@ function spinner() {
 }
 
 
-# These codes are from rtinst and QuickBox
-function apt_install() {
-    local install_list
-    # [[ -z "$OutputLOG" ]] && echo "ERROR: No output" && exit 1
-    packages=("$@")  # arg=("$@") packages=("${arg[@]:1}")
+function apt_install_check() {
+    unset apt_install_list skip_list                                                                                # do not use local here
+    packages=("$@")                                                                                                 # arg=("$@") packages=("${arg[@]:1}")
     [[ -z "$packages" ]] && echo "ERROR: No packages" | tee -a $OutputLOG && exit 1
     for package_name in "${packages[@]}" ; do
         if [ $(apt-cache show -q=0 $package_name 2>&1 | grep -c "No packages found") -eq 0 ]; then
-            if [ $(dpkg-query -W -f='${Status}' $package_name 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
-                install_list="$install_list $package_name"
+            if [ $(dpkg-query -W -f='${Status}' $package_name 2>/dev/null | grep -c "ok installed") -eq 0 ]; then   # Not installed yet
+                apt_install_list="$apt_install_list $package_name"
             fi
         else
-            echo "$package_name not found, skipping" 2>&1 | tee -a "$OutputLOG"
+            skip_list="$skip_list $package_name"
+          # echo "$package_name not found, skipping" 2>&1 | tee -a "$OutputLOG"
         fi
     done
-    # test -z "$install_list" || apt-get -y install $install_list >> "$OutputLOG" 2>&1
-    if [[ -n "$install_list" ]]; then
-        apt-get -y --allow-unauthenticated -f install $install_list >> "$OutputLOG" 2>&1
+    if [[ -n "$skip_list" ]]; then
+        echo "$skip_list not found, skipping" 2>&1 | tee -a "$OutputLOG"
+    fi
+}
+
+
+# apt_install_check aaa bbb ; apt_install_separate ; apt_install_check aaa bbb ; apt_install_check_after
+function apt_install_check_after() {
+    if [[ -n "$apt_install_list" ]]; then
+        echo -e "ERROR: It seems there are some package failed installation" 2>&1 | tee -a "$OutputLOG"
+        exit 1
+    fi
+}
+
+
+function apt_install_together() {
+    # test -z "$apt_install_list" || apt-get -y install "$apt_install_list" >> "$OutputLOG" 2>&1
+    if [[ -n "$apt_install_list" ]]; then
+        # apt-get -y --allow-unauthenticated -f install "$apt_install_list" >> "$OutputLOG" 2>&1
+        DEBIAN_FRONTEND=noninteractive apt-get -y --allow-unauthenticated -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install "$apt_install_list" >> "$OutputLOG" 2>&1
         if [ ! $? = 0 ]; then
             echo -e "ERROR: Failed to install packages" 2>&1 | tee -a "$OutputLOG"
             exit 1
@@ -181,22 +197,16 @@ function apt_install() {
 
 
 function apt_install_separate() {
-    # [[ -z "$OutputLOG" ]] && echo "ERROR: No output" && exit 1
-    packages=("$@")  # arg=("$@") packages=("${arg[@]:1}")
-    packages=("${arg[@]:1}")
-    [[ -z "$packages" ]] && echo_error "No packages input" # && exit 1
-    for package_name in "${packages[@]}" ; do
-        if [ $(apt-cache show -q=0 $package_name 2>&1 | grep -c "No packages found") -eq 0 ]; then
-            if [ $(dpkg-query -W -f='${Status}' $package_name 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
-                DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install $package_name >> "$OutputLOG" 2>&1 ||
-                { echo | tee -a $OutputLOG ; echo_error "Failed to install $package_name" ; }
+    if [[ -n "$apt_install_list" ]]; then
+        for package in $apt_install_list; do
+            DEBIAN_FRONTEND=noninteractive apt-get -y --allow-unauthenticated -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install $package >> "$OutputLOG" 2>&1
+            # || { echo | tee -a $OutputLOG ; echo_error "Failed to install $package" ; exit 1 ; }
+            if [ ! $? = 0 ]; then
+                echo -e "ERROR: Failed to install $package" 2>&1 | tee -a "$OutputLOG"
+                exit 1
             fi
-        else
-            # Since we use echo -ne when echo_task, so use echo to start a newline
-            echo | tee -a $OutputLOG
-            echo_info "$package_name not found, skipping"
-        fi
-    done
+        done
+    fi
 }
 
 
