options / enable options_validate_password

diff --git a/00.Installation/options b/00.Installation/options
--- a/00.Installation/options
+++ b/00.Installation/options
@@ -3,8 +3,8 @@
 # https://github.com/Aniverse/inexistence
 # Author: Aniverse
 #
-# script_update=2020.06.17
-# script_version=r10004
+# script_update=2020.06.27
+# script_version=r10005
 # This var will recover other script's var when source
 #
 ################################################################################################
@@ -48,6 +48,8 @@ Example:
   $script_cmd -u aniverse -p ajYeTGRkFw42 -y --de 1.3.15 --qb no --rt no  \\
   --hostname myseedbox --flexget --no-bbr --rclone --tweaks --tr-deb --vnc \\
   --no-system-upgrade --no-reboot --no-source-change --no-filebrowser
+
+中文介绍：https://github.com/Aniverse/inexistence#installation-guide
 "
     exit
 }
@@ -56,8 +58,8 @@ Example:
 
 function opts_action () {
     while [ -n "$1" ] ; do case "$1" in
-        -u | --user       ) iUser=$2          ; shift 2 ;;
-        -p | --password   ) iPass=$2          ; shift 2 ;;
+        -u | --user       ) iUser=$2 ; options_validate_username ; shift 2 ;;
+        -p | --password   ) iPass=$2 ; options_validate_password ; shift 2 ;;
         -b | --branch     ) iBranch=$2        ; shift 2 ;;
     
         --de              ) de_version=$2     ; shift 2 ;;
@@ -111,9 +113,6 @@ function opts_action () {
     
         -- ) shift ; break ;;
     esac ; done
-
-    [[ -n $iUser ]] && options_validate_username
-#   [[ -n $iPass ]] && options_validate_password
 }
 
 function options_validate_username() {
@@ -121,21 +120,35 @@ function options_validate_username() {
     count=0
     count=$(echo -n "$iUser" | wc -c)
     if $(echo "${reserved_names[@]}" | grep -wq "$iUser"); then
-        echo -e "Do not use reversed user name ! 这个用户名不可用，换一个吧"
+        echo -e "ERROR: Do not use reversed user name ! 这个用户名不可用，换一个吧"
         exit 1
     elif [[ $count -lt 3 || $count -gt 32 ]]; then
-        echo -e "User name cannot less than 3 or more than 32 characters ! 用户名长度 3-32 位"
+        echo -e "ERROR: User name cannot less than 3 or more than 32 characters ! 用户名长度 3-32 位"
         exit 1
     elif ! [[ "$iUser" =~ ^[a-z][-a-z0-9_]*$ ]]; then
-        echo -e "Your username must start from a lower case letter and the username"
+        echo -e "ERROR: Your username must start from a lower case letter and the username"
         echo -e "must contain only lowercase letters, numbers, hyphens, and underscores."
-        echo -e "用户名必须由小写字母开头，只能用小写字母、数字、连字符、下划线"
+        echo -e "用户名必须由小写字母开头，只能使用小写字母、数字、连字符、下划线"
         exit 1
     fi
 }
 
-# This requirement is higher than ask_password
+
 function options_validate_password() {
+    if [ ${#iPass} -lt 8 ]; then                     # At least [8] chars long
+        echo -e "ERROR: Password must be at least [8] chars long 密码长度至少要有 8 位"
+        exit 1
+    elif ! echo "$iPass" | grep -q '[0-9]'; then     # At least [1] number
+        echo -e "ERROR: Password must have at least [1] number 密码中必须包含数字"
+        exit 1
+    elif ! echo "$iPass" | grep -q '[a-zA-Z]'; then  # At least [1] letter
+        echo -e "ERROR: Password must have at least [1] letter 密码中必须包含英文字母"
+        exit 1
+    fi
+}
+
+
+function options_validate_password_quickbox_lite() {
     count=0
     count=$(echo -n "$iPass" | wc -c)
     strength=$(echo "$iPass" | grep -P '(?=^.{8,32}$)(?=^[^\s]*$)(?=.*\d)(?=.*[A-Z])(?=.*[a-z])')
@@ -144,11 +157,11 @@ function options_validate_password() {
         exit 1
     else
         if [[ $strength == "" ]]; then
-        echo -e "Your password must consist:"
-        echo -e "1. digital numbers"
-        echo -e "2. at least one lower case letter"
-        echo -e "3. one upper case letter"
-        exit 1
+            echo -e "Your password must consist:"
+            echo -e "1. digital numbers"
+            echo -e "2. at least one lower case letter"
+            echo -e "3. one upper case letter"
+            exit 1
         fi
     fi
 }
