update ip address validation

diff --git a/00.Installation/script/mingling b/00.Installation/script/mingling
--- a/00.Installation/script/mingling
+++ b/00.Installation/script/mingling
@@ -118,8 +118,8 @@ shanshuo=$(tput blink); wuguangbiao=$(tput civis); guangbiao=$(tput cnorm)
 # 定义变量 --------------------------------------------------------------------------------
 
 ### 是否为 IP 地址 ###
-function isValidIpAddress() {
-	echo $1 | grep -qE '^[0-9][0-9]?[0-9]?\.[0-9][0-9]?[0-9]?\.[0-9][0-9]?[0-9]?\.[0-9][0-9]?[0-9]?$'
+function isIpAddress() {
+	echo $1 | grep -qE '((2[0-4]\d|25[0-5]|[01]?\d\d?)\.){3}(2[0-4]\d|25[0-5]|[01]?\d\d?)'
 }
 
 ### 是否为内网 IP 地址 ###
@@ -132,16 +132,15 @@ opsy=$( get_opsy )
 kern=$( uname -r )
 
 echo
-echo "${bold}Checking your server's public IP address ...${normal}"
+echo "${bold}正在检查盒子的公网 IPv4、IPv6 地址 ...${normal}"
 # echo "${bold}If you stick here for quite a while, please press ${red}Ctrl+C${white} to stop the script${normal}"
 serveripv4=$(ip route get 8.8.8.8 | awk 'NR==1 {print $NF}')
-isInternalIpAddress "$serveripv4" || serveripv4=$(wget --no-check-certificate --timeout=10 -qO- http://v4.ipv6-test.com/api/myip.php)
-isValidIpAddress "$serveripv4" || serveripv4=$(curl -s --connect-timeout 10 ip.cn | awk -F'：' '{print $2}' | awk '{print $1}')
-isValidIpAddress "$serveripv4" || serveripv4=$(curl -s --connect-timeout 10 ifconfig.me)
-isValidIpAddress "$serveripv4" || echo "${bold}${red}ERROR${red} Failed to detect your public IPv4 address ...${normal}"
-
-serveripv6=$( wget --no-check-certificate -qO- -t1 -T2 ipv6.icanhazip.com )
-
+isInternalIpAddress "$serveripv4" || serveripv4=$(wget --no-check-certificate -T10 -qO- http://v4.ipv6-test.com/api/myip.php)
+isIpAddress "$serveripv4" || serveripv4=$(curl -s -T10 ip.cn | awk -F'：' '{print $2}' | awk '{print $1}')
+isIpAddress "$serveripv4" || serveripv4=$(curl -s -T10 ifconfig.me)
+isIpAddress "$serveripv4" || echo "${bold}${red}ERROR${red} Failed to detect your public IPv4 address ...${normal}"
+serveripv6=$( wget --no-check-certificate -qO- -t1 -T7 ipv6.icanhazip.com )
+echo "${bold}正在检查盒子的各项参数 ...${normal}"
 disk_size1=($( LANG=C df -hPl | grep -wvE '\-|none|tmpfs|devtmpfs|by-uuid|chroot|Filesystem' | awk '{print $2}' ))
 disk_size2=($( LANG=C df -hPl | grep -wvE '\-|none|tmpfs|devtmpfs|by-uuid|chroot|Filesystem' | awk '{print $3}' ))
 disk_total_size=$( calc_disk ${disk_size1[@]} )
