function / fix getopt

diff --git a/00.Installation/install/function b/00.Installation/install/function
--- a/00.Installation/install/function
+++ b/00.Installation/install/function
@@ -3,8 +3,8 @@
 # https://github.com/Aniverse/inexistence
 # Author: Aniverse
 #
-script_update=2019.05.13
-script_version=r10004
+script_update=2019.05.14
+script_version=r10005
 ################################################################################################
 
 usage_guide() {
@@ -13,13 +13,13 @@ source /etc/inexistence/00.Installation/install/function
 
 ################################################################################################ Get options
 
-OPTS=$(getopt -n "$0" --long "output:" -- "$@")
+OPTS=$(getopt -n "$0" -o "a:" --long "output:" -- "$@")
 eval set -- "$OPTS"
 
 while true; do
     case "$1" in
-        --output        ) output="$2" ; shift ; shift ;;
-        *) break ;;
+        -a | --output     ) output="$2" ; shift 2 ;;
+        *  ) echo "Invalid option $1" ; break ; exit 1 ;;
     esac
 done
 
