ins_lt / mirror update from ins_de

diff --git a/00.Installation/install/install_libtorrent_rasterbar b/00.Installation/install/install_libtorrent_rasterbar
--- a/00.Installation/install/install_libtorrent_rasterbar
+++ b/00.Installation/install/install_libtorrent_rasterbar
@@ -3,14 +3,14 @@
 # https://github.com/Aniverse/inexistence
 # Author: Aniverse
 #
-# 2018.10.29
-# 1.1.3
+# update=2018.11.17
+# version=1.14
 #
+# --------- Usage ---------
 # wget -qO ltr https://github.com/Aniverse/inexistence/raw/master/00.Installation/install/install_libtorrent_rasterbar
-# bash ltr -v 1.1.10       bash ltr -m deb       bash ltr -b RC_1_1
+# bash ltr -v 1.1.11       bash ltr -m deb       bash ltr -b RC_1_1
 
-
-OutputLOG=/etc/inexistence/01.Log/install_libtorrent_rasterbar.txt # /dev/null
+OutputLOG=/etc/inexistence/01.Log/install_libtorrent_rasterbar.txt    # /dev/null
 DebLocation=/etc/inexistence/01.Log/DebPackages
 SCLocation=/etc/inexistence/01.Log/SourceCodes
 LOCKLocation=/etc/inexistence/01.Log/Lock
@@ -24,10 +24,24 @@ heibaise=${black}${on_white}; heihuangse=${on_yellow}${black}; jiacu=${normal}${
 CW="${bold}${baihongse} ERROR ${jiacu}";ZY="${baihongse}${bold} ATTENTION ${jiacu}";JG="${baihongse}${bold} WARNING ${jiacu}"
 
 # Sustem check
-CODENAME=`  cat /etc/os-release | grep VERSION= | tr '[A-Z]' '[a-z]' | sed 's/\"\|(\|)\|[0-9.,]\|version\|lts//g' | awk '{print $2}'  `
+CODENAME=$( cat /etc/os-release | grep VERSION= | tr '[A-Z]' '[a-z]' | sed 's/\"\|(\|)\|[0-9.,]\|version\|lts//g' | awk '{print $2}' )
 
 # Get options
 OPTS=$(getopt -n "$0" -o m:v:b: --long "install-mode:,version:,branch:" -- "$@")
+
+spinner() {
+    local pid=$1
+    local delay=0.25
+    local spinstr='|/-\'
+    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
+        local temp=${spinstr#?}
+        printf " [${bold}${yellow}%c${normal}]  " "$spinstr"
+        local spinstr=$temp${spinstr%"$temp"}
+        sleep $delay
+        printf "\b\b\b\b\b\b"
+    done
+    printf "    \b\b\b\b"
+}
 
 
 
@@ -59,13 +73,13 @@ esac
 [[ -z $MAXCPUS ]] && MAXCPUS=$(nproc)
 
 # Transform version to branch
-[[ ` echo $version | grep -Eo "[012]\.[0-9]+\.[0-9]+" ` ]] && branch=` echo libtorrent-$version | sed "s/\./_/g" `
+[[ $( echo $version | grep -Eo "[012]\.[0-9]+\.[0-9]+" ) ]] && branch=$( echo libtorrent-$version | sed "s/\./_/g" )
 
 # Check if input branch exists
 [[ ! -z $branch ]] && [[ ! $( wget -qO- "https://github.com/arvidn/libtorrent" | grep data-name | cut -d '"' -f2 | grep -P "$branch\b" ) ]] && { echo -e "\n${CW} No such branch!\n" ; exit 1 ; }
 
-# Use RC_1_0 if not specified
-[[ -z $branch ]] && branch=RC_1_0
+# Use RC_1_1 if not specified
+[[ -z $branch ]] && branch=RC_1_1
 
 # Determin RC_1_0 and RC_1_1's version
 # [[ $branch == RC_1_0 ]] && version=1.0.11
@@ -80,6 +94,7 @@ esac
 # Random Number，用于区分下载下来的 lt 源码是哪一次下来的
 [[ $mode == source ]] && RN=$(shuf -i 1-999 -n1)
 
+rm -f /tmp/lt.1.lock /tmp/lt.2.lock
 
 
 
@@ -89,13 +104,12 @@ function _install_lt_dependencies() {
 
 echo -ne "Install libtorrent-rasterbar build dependencies ... " | tee -a $OutputLOG
 
-{ apt-get install -y                                                                \
+apt-get install -y                                                                \
 build-essential pkg-config autoconf automake libtool git checkinstall               \
 libboost-dev libboost-system-dev libboost-chrono-dev libboost-random-dev libssl-dev \
 geoip-database libgeoip-dev                                                         \
 libboost-python-dev                                                                 \
-zlib1g-dev >> $OutputLOG 2>&1 ; } && \
-echo "${green}${bold}DONE${normal}" || echo "${red}${bold}FAILED${normal}"
+zlib1g-dev >> $OutputLOG 2>&1 && touch /tmp/lt.1.lock || touch /tmp/lt.2.lock
 
 touch $LOCKLocation/libtorrent-rasterbar.dependencies.lock ; }
 
@@ -107,18 +121,6 @@ touch $LOCKLocation/libtorrent-rasterbar.dependencies.lock ; }
 function _install_lt_source() {
 
 [[ ! -f $LOCKLocation/libtorrent-rasterbar.dependencies.lock ]] && _install_lt_dependencies
-
-# if [[ $branch =~ (RC_1_0|RC_1_1|RC_1_2|master) ]]; then
-#     echo -ne "Install libtorrent-rasterbar $branch ($version) from source code ... " | tee -a $OutputLOG
-# else
-#     echo -ne "Install libtorrent-rasterbar $version from source code ... " | tee -a $OutputLOG
-# fi
-
-if [[ ` echo $branch | grep -Eo "[012]_[0-9]_[0-9]+" ` ]]; then
-    echo -ne "Install libtorrent-rasterbar ${bold}${cyan}$version${normal} from source codes ... " | tee -a $OutputLOG
-else
-    echo -ne "Install libtorrent-rasterbar ${bold}$branch branch (${cyan}$version${jiacu})${normal} from source codes ... " | tee -a $OutputLOG
-fi
 
 git clone --depth=1 -b $branch https://github.com/arvidn/libtorrent libtorrent-$version-$RN >> $OutputLOG 2>&1
 cd libtorrent-$version-$RN
@@ -133,9 +135,10 @@ mkdir -p doc-pak && echo "an efficient feature complete C++ bittorrent implement
             --disable-debug --enable-encryption --with-libgeoip=system CXXFLAGS=-std=c++11  >> $OutputLOG 2>&1 # For both Deluge and qBittorrent
 make -j$MAXCPUS >> $OutputLOG 2>&1
 
-# 如果之前 dpkg 安装过一次，包名不一样的话，这一次 checkinstall 就会失败，所以失败后保险起见再 make install 试一次
-{ checkinstall -y --pkgname=libtorrent-rasterbar --pkggroup libtorrent --pkgversion $version >> $OutputLOG 2>&1
-} && echo "${green}${bold}DONE${normal}" || { make install >> $OutputLOG 2>&1 || echo "${red}${bold}FAILED${normal}" ;}
+# 如果之前 dpkg 安装过一次，包名不一样的话，这一次 checkinstall 就会失败，所以失败后保险起见，失败了的话再 make install 试一次
+checkinstall -y --pkgname=libtorrent-rasterbar --pkggroup libtorrent --pkgversion $version >> $OutputLOG 2>&1 && 
+touch /tmp/lt.1.lock || {
+make install >> $OutputLOG 2>&1 && touch /tmp/lt.1.lock || touch /tmp/lt.2.lock ; }
 
 cp -f libtorrent-rasterb*.deb $DebLocation
 touch $LOCKLocation/libtorrent-rasterbar.lock
@@ -150,8 +153,6 @@ function _install_lt_deb() {
 
 [[ ! -f $LOCKLocation/libtorrent-rasterbar.dependencies.lock ]] && _install_lt_dependencies
 
-echo -ne "Install libtorrent-rasterbar ${bold}${cyan}1.0.11${normal} from pre-compiled deb package ... " | tee -a $OutputLOG
-
 if   [[ $CODENAME == jessie  ]]; then
     wget -O lt.$CODENAME.1.0.11.deb https://github.com/Aniverse/BitTorrentClientCollection/raw/master/Deb%20Package/Jessie/libtorrent-rasterbar_1.0.11_jessie_amd64.deb         >> $OutputLOG 2>&1
 elif [[ $CODENAME == xenial  ]]; then
@@ -162,7 +163,7 @@ elif [[ $CODENAME == bionic  ]]; then
     wget -O lt.$CODENAME.1.0.11.deb https://github.com/Aniverse/BitTorrentClientCollection/raw/master/Deb%20Package/Bionic/libtorrent-rasterbar-seedbox_1.0.11_bionic_amd64.deb >> $OutputLOG 2>&1
 fi
 
-{ dpkg -i lt.deb >> $OutputLOG 2>&1 ; } && echo "${green}${bold}DONE${normal}" || echo "${red}${bold}FAILED${normal}"
+dpkg -i lt.deb >> $OutputLOG 2>&1 && touch /tmp/lt.1.lock || touch /tmp/lt.2.lock
 touch $LOCKLocation/libtorrent-rasterbar.lock
 touch $LOCKLocation/libtorrent-rasterbar.deb.lock ; }
 
@@ -173,17 +174,16 @@ touch $LOCKLocation/libtorrent-rasterbar.deb.lock ; }
 # Install from repository
 function _install_lt_apt() {
 
-version=` apt-cache policy python-libtorrent | grep -B1 http | grep -Eo "[012]\.[0-9]+.[0-9]+" | head -n1 `
-[[ -z $version ]] && {
-[[ $CODENAME == bionic  ]] && version=1.1.5 ; [[ $CODENAME == xenial ]] && version=1.0.7 ; [[ $CODENAME == trusty ]] && version=0.16.13
-[[ $CODENAME == stretch ]] && version=1.1.1 ; [[ $CODENAME == jessie ]] && version=0.16.18 ; }
-
-echo -ne "Install libtorrent-rasterbar ${bold}${cyan}$version${normal} from repository ... " | tee -a $OutputLOG
-
-{ apt-get -y install libtorrent-rasterbar-dev python-libtorrent >> $OutputLOG 2>&1 ; } && echo "${green}${bold}DONE${normal}" || echo "${red}${bold}FAILED${normal}"
+apt-get -y install libtorrent-rasterbar-dev python-libtorrent >> $OutputLOG 2>&1 && touch /tmp/lt.1.lock || touch /tmp/lt.2.lock
 
 touch $LOCKLocation/libtorrent-rasterbar.lock
 touch $LOCKLocation/libtorrent-rasterbar.apt.lock ; }
+
+[[ $mode == apt ]] && {
+version=` apt-cache policy python-libtorrent | grep -B1 http | grep -Eo "[012]\.[0-9]+.[0-9]+" | head -n1 `
+[[ -z $version ]] && {
+[[ $CODENAME == bionic  ]] && version=1.1.5 ; [[ $CODENAME == xenial ]] && version=1.0.7 ; [[ $CODENAME == trusty ]] && version=0.16.13
+[[ $CODENAME == stretch ]] && version=1.1.1 ; [[ $CODENAME == jessie ]] && version=0.16.18 ; } ; }
 
 
 
@@ -191,21 +191,26 @@ touch $LOCKLocation/libtorrent-rasterbar.apt.lock ; }
 
 mkdir -p $SCLocation $DebLocation $LOCKLocation
 cd       $SCLocation
-
-cat>>$OutputLOG<<EOF
-
-
-
-$(date "+%Y.%m.%d.%H.%M.%S")   $RN
-
-
-
-EOF
+echo "\n\n\n$(date "+%Y.%m.%d.%H.%M.%S")   $RN\n\n\n" >> $OutputLOG
 
 case $mode in
-    apt     ) _install_lt_apt                                ;;
-    deb     ) _install_lt_deb      ;;
-    source  ) _install_lt_source  ;;
+    apt     ) echo -ne "Install libtorrent-rasterbar ${bold}${cyan}$version${normal} from repository ... " | tee -a $OutputLOG
+              _install_lt_apt & spinner $!
+              ;;
+    deb     ) echo -ne "Install libtorrent-rasterbar ${bold}${cyan}1.0.11${normal} from pre-compiled deb package ... " | tee -a $OutputLOG
+              _install_lt_deb & spinner $!
+              ;;
+    source  ) if [[ ` echo $branch | grep -Eo "[012]_[0-9]_[0-9]+" ` ]]; then
+                  echo -ne "Install libtorrent-rasterbar ${bold}${cyan}$version${normal} from source codes ... " | tee -a $OutputLOG
+              else
+                  echo -ne "Install libtorrent-rasterbar ${bold}$branch branch (${cyan}$version${jiacu})${normal} from source codes ... " | tee -a $OutputLOG
+              fi
+              _install_lt_source & spinner $!
+              ;;
 esac
 
 cd ; ldconfig
+
+[[ -f /tmp/de.1.lock ]] && echo -e " ${green}${bold}DONE${normal}"
+[[ -f /tmp/de.2.lock ]] && echo -e " ${red}${bold}FAILED${normal}"
+[[ ! -f /tmp/de.1.lock ]] && [[ ! -f /tmp/de.2.lock ]] && echo -e " ${red}${bold}Unknown State${normal}"
