Update install_de

diff --git a/00.Installation/install/install_deluge b/00.Installation/install/install_deluge
--- a/00.Installation/install/install_deluge
+++ b/00.Installation/install/install_deluge
@@ -3,18 +3,14 @@
 # https://github.com/Aniverse/inexistence
 # Author: Aniverse
 #
-# 2018.07.09
-# 1.0.0.test
+# 2018.10.29
+# 1.0.1
+# wget -qO de https://github.com/Aniverse/inexistence/raw/master/00.Installation/install/install_libtorrent_rasterbar
+# bash de -v 1.3.9
 
 OutputLOG=/etc/inexistence/01.Log/install_deluge.txt # /dev/null
 SCLocation=/etc/inexistence/01.Log/SourceCodes
 LOCKLocation=/etc/inexistence/01.Log/Lock
-
-cat>>$OutputLOG<<EOF
-
-$(date "+%Y.%m.%d.%H.%M.%S")
-
-EOF
 
 # Colors
 black=$(tput setaf 0); red=$(tput setaf 1); green=$(tput setaf 2); yellow=$(tput setaf 3); blue=$(tput setaf 4); magenta=$(tput setaf 5); cyan=$(tput setaf 6); white=$(tput setaf 7);
@@ -25,6 +21,7 @@ heibaise=${black}${on_white}; heihuangse=${on_yellow}${black}; jiacu=${normal}${
 CW="${bold}${baihongse} ERROR ${jiacu}";ZY="${baihongse}${bold} ATTENTION ${jiacu}";JG="${baihongse}${bold} WARNING ${jiacu}"
 
 # Sustem check
+DISTRO=`  awk -F'[= "]' '/PRETTY_NAME/{print $3}' /etc/os-release  `
 CODENAME=`  cat /etc/os-release | grep VERSION= | tr '[A-Z]' '[a-z]' | sed 's/\"\|(\|)\|[0-9.,]\|version\|lts//g' | awk '{print $2}'  `
 
 # Get options
@@ -32,14 +29,13 @@ OPTS=$(getopt -n "$0" -o m:v:b: --long "install-mode:,version:,branch:" -- "$@")
 
 
 
-DeSource="http://download.deluge-torrent.org/source"
-
 eval set -- "$OPTS"
 
 while true; do
   case "$1" in
     -m | --install-mode ) mode="$2"     ; shift ; shift ;;
     -v | --version      ) version="$2"  ; shift ; shift ;;
+    -b | --branch       ) branch="$2"   ; shift ; shift ;;
      * ) break ;;
   esac
 done
@@ -48,56 +44,78 @@ case $mode in
     apt     ) sleep 0  ;;
     ppa     ) sleep 0  ;;
     source  ) sleep 0  ;;
-    ""   | *) echo -e "\n${CW} Install mode must be specified as apt, ppa or source${normal}\n"   ;;
+    alt     ) sleep 0  ;;
+    ""   | *) echo -e "\n${CW} Install mode must be specified as apt, ppa, source or alt${normal}\n"   ;;
 esac
 
+DeSource="http://download.deluge-torrent.org/source"
+
+# Check available version
 AvailableVersion=$(  wget -qO - $DeSource | grep -o "deluge-[0-9]\{1,2\}\.[0-9]\{1,2\}\.[0-9]\{1,2\}\.tar.gz" | sort -uV | grep -o "[0-9]\{1,2\}\.[0-9]\{1,2\}\.[0-9]\{1,2\}"  )
+
+# Check if input branch exists
+[[ ! -z $branch ]] && [[ ! $( wget -qO- "https://github.com/deluge-torrent/deluge" | grep data-name | cut -d '"' -f2 | grep -P "$branch\b" ) ]] && { echo -e "\n${CW} No such branch!\n" ; exit 1 ; }
+
+# Random Number
+[[ $mode =~ (source|alt) ]] && RN=$(shuf -i 1-999 -n1)
 
 
 
 
 
 # Install from source code
-# Guide from
-# https://dev.deluge-torrent.org/wiki/Installing/Source#BuildingandInstalling
 function _install_de_source() {
 
-echo -e "Install from source code \nbracnh $branch, version $version\n" >> $OutputLOG 2>&1
+echo -ne "Install deluge build dependencies ... " | tee -a $OutputLOG
 
 # Install Dependencies without python-libtorrent (libtorrent-rasterbar should have been built before)
-apt-get install -y python python-twisted python-openssl python-setuptools intltool python-xdg python-chardet geoip-database python-notify python-pygame python-glade2 librsvg2-common xdg-utils python-mako >> $OutputLOG 2>&1
-# Fetch source files
-wget $DeSource/deluge-$version.tar.gz
-tar xf deluge-$version.tar.gz && rm -f deluge-$version.tar.gz && cd deluge-$version
+apt-get install -y python python-twisted python-openssl python-setuptools intltool python-xdg python-chardet geoip-database python-notify python-pygame python-glade2 librsvg2-common xdg-utils python-mako >> $OutputLOG 2>&1 && \
+echo "${green}${bold}DONE${normal}" || echo "${red}${bold}FAILED${normal}"
 
-python setup.py build  > /dev/null ; python setup.py install --install-layout=deb  > /dev/null ; cd
+# Fetch source files
+echo -e "Install deluge ${bold}${cyan}$version${normal} from source codes ... " | tee -a $OutputLOG
+
+wget $DeSource/deluge-$version.tar.gz         >> $OutputLOG 2>&1
+tar xf deluge-$version.tar.gz                 >> $OutputLOG 2>&1
+rm -f deluge-$version.tar.gz                  >> $OutputLOG 2>&1
+cd deluge-$version
+
+python setup.py build                         >> $OutputLOG 2>&1
+python setup.py install --install-layout=deb  >> $OutputLOG 2>&1 && \
+echo "${green}${bold}DONE${normal}" || echo "${red}${bold}FAILED${normal}"
 
 touch $LOCKLocation/deluge
 touch $LOCKLocation/deluge.source.$version.lock ; }
 
 
 
+
+
 # Install from PPA
 function _install_de_ppa() {
 
-echo -e "Install from pre-compiled deb package\n" >> $OutputLOG 2>&1
+latest_stable=1.3.15
+latest_stable=` wget -qO- https://dev.deluge-torrent.org/wiki/ReleaseNotes | grep wiki/ReleaseNotes | grep -Eo "[12]\.[0-9.]+" | sed 's/">/ /' | awk '{print $1}' | head -n1 `
 
-if [[ $DISTRO == Debian ]]; then
+echo -ne "Install deluge ${bold}${cyan}$latest_stable${normal} from stable ppa ... " | tee -a $OutputLOG
 
-    add-apt-repository 'deb http://ppa.launchpad.net/deluge-team/ppa/ubuntu trusty main'  >> $OutputLOG 2>&1
-    apt-get update                                                                        >> $OutputLOG 2>&1
-    apt-get install -t trusty libtorrent-rasterbar8 python-libtorrent                     >> $OutputLOG 2>&1
-    apt-get install -t trusty deluged deluge-web                                          >> $OutputLOG 2>&1
+if   [[ $DISTRO == Debian ]]; then
+
+    echo 'deb http://ppa.launchpad.net/deluge-team/ppa/ubuntu trusty main'        >> /etc/apt/sources.list
+    apt-get update                                                                >> $OutputLOG 2>&1
+    apt-get install -t trusty deluge deluged deluge-web deluge-console deluge-gtk >> $OutputLOG 2>&1 && && \
+    echo "${green}${bold}DONE${normal}" || echo "${red}${bold}FAILED${normal}"
 
 elif [[ $DISTRO == Ubuntu ]]; then
 
     add-apt-repository -y ppa:deluge-team/ppa         >> $OutputLOG 2>&1
     apt-get update                                    >> $OutputLOG 2>&1
-    apt-get install python-libtorrent                 >> $OutputLOG 2>&1
-    apt-get install -y --allow-change-held-packages --allow-downgrades libtorrent-rasterbar8=1.0.11-1~xenial~ppa1.1 python-libtorrent=1.0.11-1~xenial~ppa1.1 >> $OutputLOG 2>&1
-    apt-mark hold python-libtorrent                   >> $OutputLOG 2>&1
-    apt-mark hold libtorrent-rasterbar8               >> $OutputLOG 2>&1
-    apt-get install -y deluged deluge-web             >> $OutputLOG 2>&1
+  # apt-get install python-libtorrent                 >> $OutputLOG 2>&1
+  # apt-get install -y --allow-change-held-packages --allow-downgrades libtorrent-rasterbar8=1.0.11-1~xenial~ppa1.1 python-libtorrent=1.0.11-1~xenial~ppa1.1 >> $OutputLOG 2>&1
+  # apt-mark hold python-libtorrent                   >> $OutputLOG 2>&1
+  # apt-mark hold libtorrent-rasterbar8               >> $OutputLOG 2>&1
+    apt-get install -t trusty deluge deluged deluge-web deluge-console deluge-gtk >> $OutputLOG 2>&1 && \
+    echo "${green}${bold}DONE${normal}" || echo "${red}${bold}FAILED${normal}"
 
 fi
 
@@ -106,12 +124,23 @@ touch $LOCKLocation/deluge.ppa.lock ; }
 
 
 
+
+
 # Install from repository
-function _install_de_apt() { echo -e "Install from repository\n" >> $OutputLOG 2>&1
-apt-get install -y deluged deluge-web                            >> $OutputLOG 2>&1
+function _install_de_apt() {
+
+version=` apt-cache policy deluge | grep -B1 http | grep -Eo "[012]\.[0-9]+.[0-9]+" | head -n1 `
+[[ -z $version ]] && {
+[[ $CODENAME == bionic  ]] && version=1.3.15 ; [[ $CODENAME == xenial ]] && version=1.3.12 ; [[ $CODENAME == trusty ]] && version=1.3.6
+[[ $CODENAME == stretch ]] && version=1.3.13 ; [[ $CODENAME == jessie ]] && version=1.3.10 ; }
+
+echo -ne "Install deluge ${bold}${cyan}$version${normal} from repository ... " | tee -a $OutputLOG
+
+apt-get install -y deluge deluged deluge-web deluge-console deluge-gtk >> $OutputLOG 2>&1 && \
+echo "${green}${bold}DONE${normal}" || echo "${red}${bold}FAILED${normal}"
+
 touch $LOCKLocation/deluge.lock
 touch $LOCKLocation/deluge.apt.lock ; }
-
 
 
 
@@ -120,10 +149,21 @@ touch $LOCKLocation/deluge.apt.lock ; }
 mkdir -p $SCLocation $LOCKLocation
 cd       $SCLocation
 
+cat>>$OutputLOG<<EOF
+
+
+
+$(date "+%Y.%m.%d.%H.%M.%S")   $RN
+
+
+
+EOF
+
 case $mode in
     apt     ) _install_de_apt     ;;
     ppa     ) _install_de_ppa     ;;
     source  ) _install_de_source  ;;
+    alt     ) _install_de_alt     ;;
 esac
 
 cd
