ins_delt / update getopt

diff --git a/00.Installation/install/install_libtorrent_rasterbar b/00.Installation/install/install_libtorrent_rasterbar
--- a/00.Installation/install/install_libtorrent_rasterbar
+++ b/00.Installation/install/install_libtorrent_rasterbar
@@ -3,31 +3,41 @@
 # https://github.com/Aniverse/inexistence
 # Author: Aniverse
 #
-script_update=2019.05.13
-script_version=r10030
+script_update=2019.05.15
+script_version=r10031
 ################################################################################################
 
-usage_guide() {
+usage_for_me() {
 bash $local_packages/install/libtorrent_rasterbar -m deb2 --logbase $LogTimes
 bash <(wget -qO- https://github.com/Aniverse/inexistence/raw/master/00.Installation/install/libtorrent_rasterbar) -m deb2
 bash <(wget -qO- https://github.com/Aniverse/inexistence/raw/master/00.Installation/install/libtorrent_rasterbar) -b RC_1_2 ; }
 
 ################################################################################################ Get options
 
-OPTS=$(getopt -n "$0" -o m:v:b: --long "debug,install-mode:,version:,branch:logbase:" -- "$@")
+function show_usage() { echo " Invalid option $1
+Usage:
+      -m        Install mode, can only be specified as apt, deb, deb2, deb3 or source
+      -v        Specifiy which version of libtorrent-rasterbar to be installed
+      -b        Specifiy which branchn of libtorrent-rasterbar to be installed
+      --debug   Enable debug mode
+                Note that installing specific version cause the installation to fail
+                or the version you installed is not compatible with the version of
+                your Deluge or qBittorrent
+"
+exit 1 ; }
 
+OPTS=$(getopt -o m:v:b: -al debug,install-mode:,version:,branch:logbase: -- "$@")
+[ ! $? = 0 ] && show_usage
 eval set -- "$OPTS"
 
-while true; do
-  case "$1" in
-    -m | --install-mode ) mode="$2"     ; shift ; shift ;;
-    -v | --version      ) version="$2"  ; shift ; shift ;;
-    -b | --branch       ) branch="$2"   ; shift ; shift ;;
-         --debug        ) debug=1       ; shift ;;
-         --logbase      ) LogTimes="$2" ; shift ;;
-     * ) break ;;
-  esac
-done
+while [ -n "$1" ] ; do case "$1" in
+    -m | --install-mode ) mode="$2"     ; shift 2 ;;
+    -v | --version      ) version="$2"  ; shift 2 ;;
+    -b | --branch       ) branch="$2"   ; shift 2 ;;
+         --logbase      ) LogTimes="$2" ; shift 2 ;;
+         --debug        ) debug=1       ; shift   ;;
+    -- ) shift ; break ;;
+esac ; done
 
 ################################################################################################
 
@@ -192,7 +202,7 @@ case $mode in
               install_lt_dependencies & spinner $!
               check_status ltd ; }
 
-              echo -ne "Installing libtorrent-rasterbar ${bold}${cyan}1.1.12${normal} from pre-compiled deb package ..." | tee -a $OutputLOG
+              echo -ne "Installing libtorrent-rasterbar ${bold}${cyan}1.1.13${normal} from pre-compiled deb package ..." | tee -a $OutputLOG
               install_lt9_deb & spinner $!
               ;;
 
